### ISSUE TITLE
__generate_normal_names_queries: IndexError: pop from empty list

### ISSUE THREAD

**Issue by iksaif** [criteo/biggraphite#192] opened 2016-11-28 11:04 UTC
```
Traceback (most recent call last):
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 201, in fetchData
    seriesList = _fetchData(pathExpr,startTime, endTime, requestContext, seriesList)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 116, in _fetchData
    fetches = [(node, node.fetch(startTime, endTime)) for node in matching_nodes if node.is_leaf]
  File "/opt/graphite/webapp/graphite/storage.py", line 47, in find
    for node in finder.find_nodes(query):
  File "/opt/graphite/pypy/site-packages/biggraphite/plugins/graphite.py", line 177, in find_nodes
    metric_names, directories = glob_utils.graphite_glob(self.accessor(), query.pattern)
  File "/opt/graphite/pypy/site-packages/biggraphite/glob_utils.py", line 203, in graphite_glob
    metrics = accessor.glob_metric_names(graphite_glob)
  File "/opt/graphite/pypy/site-packages/biggraphite/drivers/cassandra.py", line 899, in glob_metric_names
    return self.__glob_names("metrics", glob)
  File "/opt/graphite/pypy/site-packages/biggraphite/drivers/cassandra.py", line 915, in __glob_names
    queries = self.__generate_normal_names_queries(table, components)
  File "/opt/graphite/pypy/site-packages/biggraphite/drivers/cassandra.py", line 986, in __generate_normal_names_queries
    idx, count = entry.pop()
IndexError: pop from empty list

```

**Comment by iksaif** [comment] 2016-11-28 11:51
cc: @dpanth3r , @erebe

**Comment by iksaif** [comment] 2016-11-28 16:57
Also:

```
2016-11-28,17:54:11.080
Traceback (most recent call last):
  File "/opt/graphite/webapp/graphite/metrics/views.py", line 138, in find_view
    matches = list( STORE.find(query, fromTime, untilTime, local=local_only) )
  File "/opt/graphite/webapp/graphite/storage.py", line 47, in find
    for node in finder.find_nodes(query):
  File "/opt/graphite/pypy/site-packages/biggraphite/plugins/graphite.py", line 177, in find_nodes
    metric_names, directories = glob_utils.graphite_glob(self.accessor(), query.pattern)
  File "/opt/graphite/pypy/site-packages/biggraphite/glob_utils.py", line 203, in graphite_glob
    metrics = accessor.glob_metric_names(graphite_glob)
  File "/opt/graphite/pypy/site-packages/biggraphite/drivers/cassandra.py", line 899, in glob_metric_names
    return self.__glob_names("metrics", glob)
  File "/opt/graphite/pypy/site-packages/biggraphite/drivers/cassandra.py", line 915, in __glob_names
    queries = self.__generate_normal_names_queries(table, components)
  File "/opt/graphite/pypy/site-packages/biggraphite/drivers/cassandra.py", line 975, in __generate_normal_names_queries
    return [self.__build_select_names_query(table, components)]
  File "/opt/graphite/pypy/site-packages/biggraphite/drivers/cassandra.py", line 1086, in __build_select_names_query
    last = components[-2]
IndexError: list index out of range
2016-11-28,17:54:11.082
Traceback (most recent call last):
  File "/opt/graphite/pypy/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/metrics/views.py", line 138, in find_view
    matches = list( STORE.find(query, fromTime, untilTime, local=local_only) )
  File "/opt/graphite/webapp/graphite/storage.py", line 47, in find
    for node in finder.find_nodes(query):
  File "/opt/graphite/pypy/site-packages/biggraphite/plugins/graphite.py", line 177, in find_nodes
    metric_names, directories = glob_utils.graphite_glob(self.accessor(), query.pattern)
  File "/opt/graphite/pypy/site-packages/biggraphite/glob_utils.py", line 203, in graphite_glob
    metrics = accessor.glob_metric_names(graphite_glob)
  File "/opt/graphite/pypy/site-packages/biggraphite/drivers/cassandra.py", line 899, in glob_metric_names
    return self.__glob_names("metrics", glob)
  File "/opt/graphite/pypy/site-packages/biggraphite/drivers/cassandra.py", line 915, in __glob_names
    queries = self.__generate_normal_names_queries(table, components)
  File "/opt/graphite/pypy/site-packages/biggraphite/drivers/cassandra.py", line 975, in __generate_normal_names_queries
    return [self.__build_select_names_query(table, components)]
  File "/opt/graphite/pypy/site-packages/biggraphite/drivers/cassandra.py", line 1086, in __build_select_names_query
    last = components[-2]
IndexError: list index out of range

```

**Comment by dpanth3r** [comment] 2016-11-28 20:35
Do you have additional logs? Maybe the pattern that caused that?

**Comment by iksaif** [comment] 2016-11-28 20:40
I do not have the query for any of these things. Looks like there is a way for part of a component to be something else than (unicode, str, bg_glob.SequenceIn).

Since this seems to happen often we could patch cassandra.py to log the glob on exception.

**Comment by dpanth3r** [comment] 2016-11-28 20:43
Looks to me like this is caused by empty queries. Could be when people start typing a query in some UI?

**Comment by iksaif** [comment] 2016-11-28 20:51
I didn't manage to generate such query

**Comment by dpanth3r** [comment] 2016-11-28 23:06
Fixed in current PR.

**Closed by dpanth3r** 2016-11-28 23:06 UTC
